Break test to check error detection

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -29,13 +29,18 @@ jobs:
 
     - name: Create a Galaxy user
       run: |
-        cat > /tmp/user.json << EOF
+        echo > /tmp/user.json << EOF
         {
           "email": "admin@example.com",
           "password": "galaxypassword",
           "username": "admin"
         }
         EOF
-        curl -s -H "x-api-key: secret" -H "Content-Type: application/json" -d @/tmp/user.json http://localhost/api/users
-
+        response=$(curl -s -H "x-api-key: secret" -H "Content-Type: application/json" -d @/tmp/user.json http://localhost/api/users)
+        echo $response | jq
+        error=$(echo $response | jq -r .err_msg)
+        if [[ -n "$error" ]]; then
+            echo "Error creating user: $error
+            exit 1
+        fi
   
